//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HabitFlow.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class HabitCategories
    {
        public int HabitCategoryId { get; set; }
        public int HabitId { get; set; }
        public int CategoryId { get; set; }
        public Nullable<System.DateTime> AssignedAt { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Habits Habits { get; set; }
    }
}
