//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HabitFlow.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class HabitRecords
    {
        public int RecordId { get; set; }
        public int HabitId { get; set; }
        public System.DateTime RecordDate { get; set; }
        public int StatusId { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual Habits Habits { get; set; }
        public virtual Statuses Statuses { get; set; }
    }
}
