//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HabitFlow.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HabitTrackerEntities : DbContext
    {
        public HabitTrackerEntities()
            : base("name=HabitTrackerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<HabitCategories> HabitCategories { get; set; }
        public virtual DbSet<HabitRecords> HabitRecords { get; set; }
        public virtual DbSet<Habits> Habits { get; set; }
        public virtual DbSet<Statuses> Statuses { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<vwCurrentStreaks> vwCurrentStreaks { get; set; }
        public virtual DbSet<vwDailyStats> vwDailyStats { get; set; }
        public virtual DbSet<vwWeeklyHabitStats> vwWeeklyHabitStats { get; set; }
    
        public virtual ObjectResult<sp_GetHabitStatsByPeriod_Result> sp_GetHabitStatsByPeriod(Nullable<int> habitId, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var habitIdParameter = habitId.HasValue ?
                new ObjectParameter("HabitId", habitId) :
                new ObjectParameter("HabitId", typeof(int));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetHabitStatsByPeriod_Result>("sp_GetHabitStatsByPeriod", habitIdParameter, startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_GetMaxStreak(Nullable<int> habitId)
        {
            var habitIdParameter = habitId.HasValue ?
                new ObjectParameter("HabitId", habitId) :
                new ObjectParameter("HabitId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_GetMaxStreak", habitIdParameter);
        }
    
        public virtual int sp_UpsertHabitRecord(Nullable<int> habitId, Nullable<System.DateTime> recordDate, Nullable<int> statusId, string note)
        {
            var habitIdParameter = habitId.HasValue ?
                new ObjectParameter("HabitId", habitId) :
                new ObjectParameter("HabitId", typeof(int));
    
            var recordDateParameter = recordDate.HasValue ?
                new ObjectParameter("RecordDate", recordDate) :
                new ObjectParameter("RecordDate", typeof(System.DateTime));
    
            var statusIdParameter = statusId.HasValue ?
                new ObjectParameter("StatusId", statusId) :
                new ObjectParameter("StatusId", typeof(int));
    
            var noteParameter = note != null ?
                new ObjectParameter("Note", note) :
                new ObjectParameter("Note", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpsertHabitRecord", habitIdParameter, recordDateParameter, statusIdParameter, noteParameter);
        }
    }
}
