//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HabitFlow.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDailyStats
    {
        public int HabitId { get; set; }
        public string HabitName { get; set; }
        public System.DateTime RecordDate { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> WeekNumber { get; set; }
        public Nullable<int> WeekDay { get; set; }
        public int StatusId { get; set; }
        public string StatusName { get; set; }
        public int IsCompleted { get; set; }
    }
}
