//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HabitFlow.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwWeeklyHabitStats
    {
        public int HabitId { get; set; }
        public string HabitName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string DayName { get; set; }
        public Nullable<int> DayOfWeek { get; set; }
        public int StatusId { get; set; }
        public string StatusName { get; set; }
        public string DisplaySymbol { get; set; }
        public int IsCompleted { get; set; }
    }
}
